#!/bin/bash

# Script to fix up the auto-generated django_generated.ts file that is generated by the zodios CLI tool
# remove .strict() and .passthrough()

FILE="./src/generatedtypes/django_generated.ts"

if [ ! -f "$FILE" ]; then
    echo "Error: File $FILE not found!"
    exit 1
fi

echo "Removing .strict() and .passthrough() from $FILE..."


# Remove .strict() and .passthrough() using sed
sed -i 's/\.strict()//g' "$FILE"
sed -i 's/\.passthrough()//g' "$FILE"
sed -i 's/import { makeApi, Zodios, type ZodiosOptions } from "@zodios\/core";/import { makeApi } from "@zodios\/core";/' "$FILE"
echo "✅ Removed all .strict() and .passthrough() calls from $FILE"

# Remove the export const api line and everything after it
sed -i '/^export const api = new Zodios(endpoints);$/,$d' "$FILE"
echo "✅ Removed export const api and createApiClient function from $FILE"

# Add the word export at the start of the line const endpoints =
sed -i 's/^const endpoints =/export const endpoints =/' "$FILE"
echo "✅ Added export to const endpoints in $FILE"

sed -i 's/const BlankEnum = z\.unknown();/const BlankEnum = z.literal("");/' "$FILE"
sed -i 's/const NullEnum = z\.unknown();/const NullEnum = z.literal(null);/' "$FILE"
echo "✅ Fixed BlankEnum and NullEnum (openapi-zod-client codegen bug workaround)"

# openapi-zod-client emits unescaped backticks in multiline enum descriptions.
perl -0pi -e 's/ActivityTypeEnum\.describe\(`.*?`\)/ActivityTypeEnum/sg' "$FILE"
perl -0pi -e 's/\n+\z/\n/' "$FILE"
echo "✅ Removed invalid ActivityTypeEnum descriptions"

echo "Complete!"
