#!/bin/bash

# Script to fix up the auto-generated django_generated.ts file.
# That is generated by the zodios CLI tool
# remove .strict() and .passthrough() 
@

FILE="./src/generatedtypes/django_generated.ts"

if [ ! -f "$FILE" ]; then
    echo "Error: File $FILE not found!"
    exit 1
fi

echo "Removing .strict() and .passthrough() from $FILE..."


# Remove .strict() and .passthrough() using sed
sed -i 's/\.strict()//g' "$FILE"
sed -i 's/\.passthrough()//g' "$FILE"
echo "✅ Removed all .strict() and .passthrough() calls from $FILE"

# Remove the export const api line and everything after it
sed -i '/^export const api = new Zodios(endpoints);$/,$d' "$FILE"
echo "✅ Removed export const api and createApiClient function from $FILE"

# Add the word export at the start of the line const endpoints =
sed -i 's/^const endpoints =/export const endpoints =/' "$FILE"
echo "✅ Added export to const endpoints in $FILE"

echo "Complete!"