export const ANIMATION_CONTROLS_BOTTOM_PX = 24;
export const ANIMATION_CONTROLS_HEIGHT_PX = 42;
export const MAP_OVERLAY_GAP_PX = 16;

export const ANIMATION_CONTROLS_RESERVED_HEIGHT_PX =
  ANIMATION_CONTROLS_BOTTOM_PX +
  ANIMATION_CONTROLS_HEIGHT_PX +
  MAP_OVERLAY_GAP_PX;
