# Generated by Django 5.2.13 on 2026-05-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='arcgis_item_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='avg_pace',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='elevation_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('Hiking', 'Hiking'), ('Running', 'Running'), ('Cycling', 'Cycling'), ('Backpacking', 'Backpacking'), ('Skiing', 'Skiing'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
