# Generated by Django 5.2.13 on 2026-06-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_migrate_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
