# Generated by Django 5.2.13 on 2026-06-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_rename_photo_created_at_to_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='track_point_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
