/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as MapRouteIdRouteImport } from './routes/map.$routeId'
import { Route as RoutesIndexRouteImport } from './routes/routes/index'
import { Route as RoutesRouteIdRouteImport } from './routes/routes/$routeId'
import { Route as RoutesNewRouteImport } from './routes/routes/new'
import { Route as RoutesRouteIdEditRouteImport } from './routes/routes/$routeId_.edit'
import { Route as RoutesRouteIdPhotosEditRouteImport } from './routes/routes/$routeId_.photos.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRouteIdRoute = MapRouteIdRouteImport.update({
  id: '/map/$routeId',
  path: '/map/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesNewRoute = RoutesNewRouteImport.update({
  id: '/routes/new',
  path: '/routes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdEditRoute = RoutesRouteIdEditRouteImport.update({
  id: '/routes/$routeId_/edit',
  path: '/routes/$routeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdPhotosEditRoute = RoutesRouteIdPhotosEditRouteImport.update({
  id: '/routes/$routeId_/photos/edit',
  path: '/routes/$routeId/photos/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/map/$routeId': typeof MapRouteIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes/': typeof RoutesIndexRoute
  '/routes/$routeId/edit': typeof RoutesRouteIdEditRoute
  '/routes/$routeId/photos/edit': typeof RoutesRouteIdPhotosEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/map/$routeId': typeof MapRouteIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes': typeof RoutesIndexRoute
  '/routes/$routeId/edit': typeof RoutesRouteIdEditRoute
  '/routes/$routeId/photos/edit': typeof RoutesRouteIdPhotosEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/map/$routeId': typeof MapRouteIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes/': typeof RoutesIndexRoute
  '/routes/$routeId_/edit': typeof RoutesRouteIdEditRoute
  '/routes/$routeId_/photos/edit': typeof RoutesRouteIdPhotosEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/callback'
    | '/map/$routeId'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes/'
    | '/routes/$routeId/edit'
    | '/routes/$routeId/photos/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/callback'
    | '/map/$routeId'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes'
    | '/routes/$routeId/edit'
    | '/routes/$routeId/photos/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth/callback'
    | '/map/$routeId'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes/'
    | '/routes/$routeId_/edit'
    | '/routes/$routeId_/photos/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  MapRouteIdRoute: typeof MapRouteIdRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  RoutesNewRoute: typeof RoutesNewRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  RoutesRouteIdEditRoute: typeof RoutesRouteIdEditRoute
  RoutesRouteIdPhotosEditRoute: typeof RoutesRouteIdPhotosEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$routeId': {
      id: '/map/$routeId'
      path: '/map/$routeId'
      fullPath: '/map/$routeId'
      preLoaderRoute: typeof MapRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/new': {
      id: '/routes/new'
      path: '/routes/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof RoutesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId_/edit': {
      id: '/routes/$routeId_/edit'
      path: '/routes/$routeId/edit'
      fullPath: '/routes/$routeId/edit'
      preLoaderRoute: typeof RoutesRouteIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId_/photos/edit': {
      id: '/routes/$routeId_/photos/edit'
      path: '/routes/$routeId/photos/edit'
      fullPath: '/routes/$routeId/photos/edit'
      preLoaderRoute: typeof RoutesRouteIdPhotosEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  MapRouteIdRoute: MapRouteIdRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  RoutesNewRoute: RoutesNewRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  RoutesRouteIdEditRoute: RoutesRouteIdEditRoute,
  RoutesRouteIdPhotosEditRoute: RoutesRouteIdPhotosEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
